### ISSUE TITLE
Invalid Target Version when using react-native windows

### ISSUE THREAD

**Issue by joewood** [ReactWindows/react-native-windows#696]
I'm using `react-native-windows` version `0.33.0-rc.1` and `rnpm-plugin-winows` version `0.2.0`. When I run `react-native windows` I see the following:

```
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react-native-windows@0.33.*"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.7

npm ERR! No compatible version found: react-native-windows@0.33.*
npm ERR! Valid install targets:
npm ERR! 1.0.0, 0.33.0-rc.1, 0.33.0-rc.0, 0.32.0, 0.32.0-rc.0, 0.31.3, 0.31.2, 0.31.1, 0.31.0, 0.31.0-rc.1, 0.31.0-rc.0, 0.30.0, 0.30.0-rc.0, 0.29.2, 0.29.1, 0.29.0, 0.29.0-rc.0, 0.28.3, 0.28.2, 0.28.1, 0.28.0, 0.28.0-rc.1, 0.28.0-rc.0, 0.27.0, 0.27.0-rc, 0.2.5-rc7, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.1.0
```

It looks like the version speification of react-native-windows@0.33.* isn't matching anything in NPM. The `-rc1` is probably throwing out the semver logic.

**Comment by rozele** [comment]
Yeah, not sure if that's worth fixing.  The real problem is that we will always lag behind react-native in terms of releases, but I think that's okay.  At some point react-native will start having an LTS that we can more easily keep up with, and most developers stick to a specific version of react-native for some time.

Personally, I don't think it's a good idea to automatically install an RC version of react-native-windows.  We should, however, try to put out an error message about the availability of the `--windowsVersion` CLI option.  In the case above, you can just run:
```
react-native windows --windowsVersion 0.33.0-rc.1
```
There's already documentation for this in the FAQs on the [README](https://github.com/ReactWindows/react-native-windows/blob/master/README.md#faqs).

**Comment by rozele** [comment]
I'm going to close this for now, since its well documented in the README.  Though I do agree that at some point, we may want to do something more robust, like, when the windows version fails, print that list of available versions and ask the user to select one instead.
