### ISSUE TITLE
App can get into state where it is stuck crashing on launch

### ISSUE THREAD

**Issue by rigdern** [ReactWindows/react-native-windows#750]
If you write some JavaScript code that causes a native exception during startup, the app can get stuck in this state. Each time you launch the app, it crashes. Even after fixing the JavaScript code, the app still crashes because the old JavaScript code appears to still be used. It crashes so soon that there's no opportunity to hit "ctrl+r" to get it to download the new JavaScript bundle.

Here's an example render function which causes a native exception which terminates the app:

```
  render() {
    return (
      <View style={styles.container}>
        <Text>
          <View style={{backgroundColor: 'red'}}>
            <Text>Crash</Text>
          </View>
        </Text>
      </View>
    );
  }
}
```

As a workaround, I commented out [this line](https://github.com/ReactWindows/react-native-windows/blob/6ae4661404c2ba83cdbfe7380b2f37b82643c7f5/ReactWindows/ReactNative/UIManager/UIViewOperationQueue.cs#L471) so that the app would render nothing, not crash, and give me the opportunity to hit "ctrl+r" to download the latest bundle.

The reason this render function doesn't work is a known issue (#685).

**Comment by rozele** [comment]
This is an issue with the "feature" to reuse a cached bundle from the packager server even if the packager server is not running.  I've got a number of bugs filed against this, so I may just disable it.  Would be easy to disable by just removing [this check](https://github.com/ReactWindows/react-native-windows/blob/master/ReactWindows/ReactNative/ReactInstanceManager.cs#L386).

**Comment by rigdern** [comment]
Do they have this feature on iOS and Android? If so, do they have the same problem?

An alternative solution would be to keep track of whether or not the app crashed during the previous run and, if it did, don't use the cached bundle.

**Comment by rozele** [comment]
It's a feature on Android.  I'll have to see what the behavior is if the app crashes there.

**Comment by rozele** [comment]
I think it should display a red box.  I'm surprised.  I think the expected behavior is that it would still reuse the cached bundle, but rather than crashing the app, it would display a red box where the user could manually trigger the reload after fixing the error.  I'll try out your sample and see why the app is just crashing.

**Comment by rozele** [comment]
Okay it seems that native module exceptions are not handled by the red box.  I guess the issue here is kind of two fold, one is the missing red box handler for native modules, and the other is whether or not Text.windows.js should have caught this and turned this into a JavaScript exception before passing the manageChildren operation to the UIManager.

**Comment by rozele** [comment]
Scratch that, native module exceptions are indeed caught by the redbox, the issue is with the UIViewOperationQueue.

**Comment by rozele** [comment]
Yeah, we need something like this https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/GuardedChoreographerFrameCallback.java in order to prevent these crashes.
